# Generated by Django 3.2.8 on 2021-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('vaccine', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('token', models.IntegerField()),
            ],
            options={
                'verbose_name': 'slot',
                'verbose_name_plural': 'slots',
                'ordering': ('name',),
            },
        ),
    ]
